application: illrequest
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css
  
- url: /image
  static_dir: image

- url: /js
  static_dir: js

- url: /.*
  script: illserver.app
  
libraries:
- name: jinja2
  version: latest